import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Clock3, Dumbbell, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { FloatingActions } from "@/components/floating-actions";
import { heroImage } from "@/components/home/home-data";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

const plans=[
{name:"1 MONTH",slug:"1-month",price:"₹3,500",popular:false,features:["Gym Access","All Equipment","Locker Room","Floor Coach Support"]},
{name:"3 MONTHS",slug:"3-months",price:"₹9,000",popular:false,features:["Everything in 1 Month","Personal Trainer Guidance","Member Discounts","Progress Review"]},
{name:"6 MONTHS",slug:"6-months",price:"₹12,000",popular:true,features:["Everything in 3 Months","Nutrition Guidance","Body Composition Analysis","Priority Coach Support"]},
{name:"12 MONTHS",slug:"12-months",price:"₹16,000",popular:false,features:["Everything in 6 Months","Priority PT Consultation","Extended Member Discounts","Annual Transformation Review"]},
] as const;
const comparison=[["Gym Access",1,1,1,1],["All Equipment",1,1,1,1],["Locker Room",1,1,1,1],["Personal Trainer Guidance",0,1,1,1],["Nutrition Guidance",0,0,1,1],["Body Composition Analysis",0,0,1,1],["Priority Support",0,0,1,1],["Member Discounts",0,1,1,1]] as const;

export function MembershipPage(){return <main className="overflow-x-clip bg-white text-[#111111]"><SiteHeader/>
  <section className="relative isolate min-h-[560px] overflow-hidden bg-[#450004] text-white"><Image src={heroImage} alt="HR Health Club memberships" fill priority className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/94 via-46% to-[#450004]/18"/><div className="relative mx-auto flex min-h-[560px] w-[min(1280px,calc(100%-2rem))] items-center py-14"><Reveal className="max-w-[650px]"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/65">MEMBERSHIP PLANS</p><h1 className="mt-6 font-[family-name:var(--font-display)] text-6xl font-black uppercase leading-[.88] sm:text-7xl lg:text-[82px]">CHOOSE THE PLAN<br/>THAT FITS<br/><span className="text-white/55">YOUR GOALS.</span></h1><div className="mt-6 h-1 w-12 bg-white"/><p className="mt-6 max-w-lg text-lg leading-8 text-white/78">Flexible plans. Premium facilities. Expert guidance. One membership, unlimited transformation.</p></Reveal></div></section>

  <section className="mx-auto w-[min(1280px,calc(100%-2rem))] py-12"><Reveal className="text-center"><h2 className="font-[family-name:var(--font-display)] text-4xl font-black uppercase">OUR <span className="text-[#7A0008]">MEMBERSHIP</span> PLANS</h2><p className="mt-2 text-sm text-[#555555]">Pick a plan, stay consistent and let the results speak.</p></Reveal><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{plans.map((plan,i)=><Reveal key={plan.name} delay={i*.04}><article className={`relative h-full overflow-hidden rounded-xl border bg-white transition hover:-translate-y-1 hover:shadow-xl ${plan.popular?"border-[#7A0008] shadow-lg":"border-[#E2D6D6]"}`}>{plan.popular&&<div className="bg-[#7A0008] py-2 text-center font-[family-name:var(--font-display)] text-[10px] font-bold uppercase tracking-[.12em] text-white">MOST POPULAR ★</div>}<div className="p-6"><p className="text-center font-[family-name:var(--font-display)] text-xl font-black uppercase">{plan.name}</p><div className="mt-4 border-y border-[#E2D6D6] py-4 text-center"><strong className={`font-[family-name:var(--font-display)] text-4xl font-black ${plan.popular?"text-[#7A0008]":""}`}>{plan.price}</strong><span className="mt-1 block text-xs text-[#555555]">Total</span></div><div className="mt-5 grid gap-3">{plan.features.map(item=><span key={item} className="flex items-start gap-3 text-sm text-[#555555]"><span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-[#F8EEEE] text-[#7A0008]"><Check size={12}/></span>{item}</span>)}</div><Link href={`/join?plan=${plan.slug}`} className={`mt-7 inline-flex w-full items-center justify-center gap-2 rounded-md px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold ${plan.popular?"bg-[#7A0008] text-white hover:bg-[#450004]":"border border-[#7A0008] text-[#7A0008] hover:bg-[#F8EEEE]"}`}>JOIN NOW <ArrowRight size={16}/></Link></div></article></Reveal>)}</div></section>

  <section className="border-y border-[#E2D6D6] bg-[#FAF8F8]"><div className="mx-auto grid w-[min(1280px,calc(100%-2rem))] grid-cols-2 md:grid-cols-3 xl:grid-cols-6">{[[Dumbbell,"NO JOINING FEE"],[Clock3,"FLEXIBLE TIMINGS"],[ShieldCheck,"CLEAN & HYGIENIC"],[Users,"EXPERT COACHES"],[Sparkles,"MEMBER DISCOUNTS"],[Users,"SUPPORTIVE COMMUNITY"]].map(([Icon,label],i)=><Reveal key={label as string} delay={i*.03}><div className="flex min-h-28 flex-col items-center justify-center border-r border-[#E2D6D6] p-4 text-center"><Icon size={25} className="text-[#7A0008]"/><span className="mt-3 font-[family-name:var(--font-display)] text-xs font-bold uppercase">{label as string}</span></div></Reveal>)}</div></section>

  <section className="mx-auto grid w-[min(1280px,calc(100%-2rem))] gap-5 py-12 lg:grid-cols-[1.35fr_.65fr]"><Reveal><div className="overflow-hidden rounded-xl border border-[#E2D6D6]"><div className="border-b border-[#E2D6D6] p-4"><h2 className="font-[family-name:var(--font-display)] text-2xl font-black uppercase">PLAN <span className="text-[#7A0008]">COMPARISON</span></h2></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-[#FAF8F8]"><tr><th className="p-3 text-left font-[family-name:var(--font-display)] uppercase">FEATURES</th>{plans.map(p=><th key={p.name} className="p-3 text-center font-[family-name:var(--font-display)] uppercase">{p.name}</th>)}</tr></thead><tbody>{comparison.map(([label,...flags])=><tr key={label as string} className="border-t border-[#E2D6D6]"><td className="p-3">{label as string}</td>{flags.map((flag,i)=><td key={`${label}-${i}`} className="p-3 text-center">{flag?<Check size={17} className="mx-auto text-emerald-600"/>:<X size={17} className="mx-auto text-[#7A0008]"/>}</td>)}</tr>)}</tbody></table></div></div></Reveal><Reveal delay={.05}><aside className="h-full rounded-xl border border-[#E2D6D6] bg-[#FAF8F8] p-6"><h2 className="font-[family-name:var(--font-display)] text-2xl font-black uppercase text-[#7A0008]">MEMBERSHIP GUIDELINES</h2><div className="mt-5 grid gap-4 text-sm leading-6 text-[#555555]">{["Membership is non-transferable.","Refunds are not applicable once membership is activated.","Carry your membership card for every visit.","Proper gym attire and shoes are mandatory.","Respect the gym, equipment and fellow members.","Consult our trainers for any assistance."].map(item=><p key={item} className="flex gap-3"><Check size={16} className="mt-1 shrink-0 text-[#7A0008]"/>{item}</p>)}</div></aside></Reveal></section>

  <section className="mx-auto mb-14 grid w-[min(1280px,calc(100%-2rem))] overflow-hidden rounded-xl bg-[#7A0008] text-white md:grid-cols-[38%_38%_24%]"><div className="relative min-h-60"><Image src={heroImage} alt="Join HR Health Club" fill className="object-cover" sizes="(min-width:768px)38vw,100vw"/><div className="absolute inset-0 bg-[#450004]/30"/></div><div className="flex flex-col justify-center p-7"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.15em] text-white/65">READY TO TRANSFORM YOUR LIFE?</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase">JOIN HR HEALTH CLUB TODAY!</h2><p className="mt-3 text-sm text-white/75">Take the first step towards a stronger, healthier and better you.</p></div><div className="flex flex-col justify-center gap-3 p-7"><Link href="/join" className="inline-flex items-center justify-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">JOIN HR FAMILY <ArrowRight size={16}/></Link><Link href="/free-trial" className="inline-flex items-center justify-center gap-2 rounded-md bg-[#450004] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold ring-1 ring-white/25">BOOK A FREE CONSULTATION <ArrowRight size={16}/></Link></div></section>
  <SiteFooter/><FloatingActions/>
</main>}
