import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Clock3, Mail, MapPin, MessageSquare, Phone, ShieldCheck, Users } from "lucide-react";
import { FaInstagram } from "react-icons/fa";
import { FloatingActions } from "@/components/floating-actions";
import { heroImage } from "@/components/home/home-data";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "Contact HR Health Club | Jodhpur", description: "Contact HR Health Club in Sardarpura, Jodhpur." };

const inputClass = "w-full rounded-md border border-[#E2D6D6] bg-white px-4 py-3 text-sm text-[#111111] outline-none transition placeholder:text-[#777] focus:border-[#7A0008] focus:ring-2 focus:ring-[#7A0008]/10";
const mapEmbedUrl = "https://www.google.com/maps?q=HR%20Health%20Club%2C%20Sardarpura%2C%20Jodhpur%2C%20Rajasthan&output=embed";
const mapDirectionsUrl = "https://www.google.com/maps/search/?api=1&query=HR+Health+Club+Sardarpura+Jodhpur+Rajasthan";

export default function Page() {
  return <main className="overflow-x-clip bg-white text-[#111111]"><SiteHeader/>
    <section className="bg-[#FAF8F8] py-14"><div className="mx-auto grid w-[min(1280px,calc(100%-2rem))] overflow-hidden rounded-xl border border-[#E2D6D6] bg-white lg:grid-cols-[.52fr_.48fr]">
      <Reveal className="relative min-h-[560px] overflow-hidden"><Image src={heroImage} alt="HR Health Club interior" fill priority className="object-cover" sizes="(min-width:1024px)52vw,100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#450004]/95 via-[#450004]/75 to-[#450004]/35"/><div className="relative flex min-h-[560px] max-w-xl flex-col justify-center p-8 text-white sm:p-10"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/70">Contact Us</p><h1 className="mt-4 font-[family-name:var(--font-display)] text-5xl font-bold uppercase leading-[.92] sm:text-6xl">We&apos;d love to hear <span className="text-white/55">from you.</span></h1><div className="mt-5 h-1 w-12 bg-white"/><p className="mt-5 max-w-md leading-8 text-white/80">Have a question, need information or ready to start your transformation journey? Get in touch with us.</p></div></Reveal>
      <Reveal delay={.05} className="p-8 sm:p-10"><p className="font-[family-name:var(--font-display)] text-2xl font-bold uppercase">Send us <span className="text-[#7A0008]">a message</span></p><div className="mt-6 grid gap-4 sm:grid-cols-2"><input className={inputClass} placeholder="Your Name" aria-label="Your name"/><input className={inputClass} placeholder="Phone Number" aria-label="Phone number"/><input className={`${inputClass} sm:col-span-2`} placeholder="Email Address" aria-label="Email address"/><input className={`${inputClass} sm:col-span-2`} placeholder="Subject" aria-label="Subject"/><textarea className={`${inputClass} min-h-32 resize-y sm:col-span-2`} placeholder="Your Message" aria-label="Your message"/><button type="button" className="group inline-flex items-center justify-center gap-2 rounded-md bg-[#7A0008] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#450004] sm:col-span-2">SEND MESSAGE <ArrowRight size={16} className="transition group-hover:translate-x-1"/></button></div><p className="mt-4 flex items-center justify-center gap-2 text-xs text-[#777]"><ShieldCheck size={14} className="text-[#7A0008]"/>We respect your privacy. Your information is safe with us.</p></Reveal>
    </div></section>

    <section className="mx-auto grid w-[min(1280px,calc(100%-2rem))] overflow-hidden rounded-xl border border-[#E2D6D6] bg-white sm:grid-cols-2 lg:grid-cols-4">{[[Clock3,"REPLY WITHIN 24 HOURS","We value your time"],[MessageSquare,"EASY & FAST RESPONSE","Quick solutions"],[ShieldCheck,"100% PRIVACY","Your data is safe"],[Users,"MEMBER SUPPORT","We are here for you"]].map(([Icon,title,copy])=><div key={title as string} className="flex items-center gap-4 border-r border-[#E2D6D6] p-5"><Icon size={24} className="text-[#7A0008]"/><div><strong className="font-[family-name:var(--font-display)] text-sm uppercase">{title as string}</strong><span className="mt-1 block text-xs text-[#777]">{copy as string}</span></div></div>)}</section>

    <section className="mx-auto grid w-[min(1280px,calc(100%-2rem))] gap-5 py-14 lg:grid-cols-[.34fr_.66fr]"><Reveal><div className="h-full rounded-xl border border-[#E2D6D6] p-7"><h2 className="font-[family-name:var(--font-display)] text-2xl font-bold uppercase">Get in <span className="text-[#7A0008]">touch</span></h2><div className="mt-6 grid gap-5 text-sm text-[#555555]"><div className="flex gap-3"><MapPin className="mt-1 shrink-0 text-[#7A0008]" size={20}/><span><strong className="block text-[#111]">ADDRESS</strong>5th B Rd, near Plant Story Restaurant, Agarwal Ki Bageechi, Sardarpura, Jodhpur, Rajasthan 342001</span></div><a href="tel:+918440070555" className="flex gap-3 hover:text-[#7A0008]"><Phone className="text-[#7A0008]" size={20}/><span><strong className="block text-[#111]">PHONE</strong>84400 70555</span></a><a href="mailto:hrhealthclubjodhpur@gmail.com" className="flex gap-3 hover:text-[#7A0008]"><Mail className="text-[#7A0008]" size={20}/><span><strong className="block text-[#111]">EMAIL</strong>hrhealthclubjodhpur@gmail.com</span></a><div className="flex gap-3"><Clock3 className="text-[#7A0008]" size={20}/><span><strong className="block text-[#111]">HOURS</strong>Mon - Sat: 5:00 AM - 10:00 PM<br/>Sunday: 6:00 AM - 2:00 PM</span></div><a href="https://www.instagram.com/hr_healthclub/" target="_blank" rel="noreferrer" className="flex gap-3 hover:text-[#7A0008]"><FaInstagram className="text-[#7A0008]" size={20}/><span><strong className="block text-[#111]">INSTAGRAM</strong>@hr_healthclub</span></a></div></div></Reveal><Reveal delay={.06}><div className="h-full min-h-[430px] overflow-hidden rounded-xl border border-[#E2D6D6] bg-[#F8EEEE]"><iframe title="HR Health Club Sardarpura Jodhpur map" src={mapEmbedUrl} className="h-full min-h-[430px] w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></Reveal></section>

    <section className="mx-auto mb-14 grid w-[min(1280px,calc(100%-2rem))] gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["VISIT THE GYM","Come experience our facilities & energy!","GET DIRECTIONS",mapDirectionsUrl],["TALK TO OUR COACHES","Have questions about training or programs?","MEET OUR COACHES","/coaches"],["BOOK A FREE CONSULTATION","Start your journey with a free 1-on-1 consultation.","BOOK NOW","/free-trial"],["MEMBERSHIP INQUIRIES","Looking for the right plan? We will help you choose.","VIEW PLANS","/membership"]].map(([title,copy,label,href])=><article key={title} className="rounded-xl border border-[#E2D6D6] bg-white p-6"><h3 className="font-[family-name:var(--font-display)] text-xl font-bold uppercase">{title}</h3><p className="mt-3 text-sm leading-6 text-[#555]">{copy}</p>{href.startsWith("http")?<a href={href} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 font-[family-name:var(--font-display)] text-xs font-bold text-[#7A0008]">{label}<ArrowRight size={14}/></a>:<Link href={href} className="mt-5 inline-flex items-center gap-2 font-[family-name:var(--font-display)] text-xs font-bold text-[#7A0008]">{label}<ArrowRight size={14}/></Link>}</article>)}</section>
    <SiteFooter/><FloatingActions/>
  </main>;
}
