import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Award, Check, ShieldCheck, Target, Trophy, UserRoundCheck, Users } from "lucide-react";
import { FloatingActions } from "@/components/floating-actions";
import { heroImage } from "@/components/home/home-data";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { coachProfiles } from "./coach-data";

const heroFeatures=[[Users,"EXPERT COACHES"],[Award,"CERTIFIED PROFESSIONALS"],[Trophy,"RESULT DRIVEN"],[Target,"PERSONALIZED ATTENTION"]] as const;
const certifications=[
{name:"ACE",src:"https://staticcdn.eacefitness.com/v-639050361360000000/images/layout/2017/dist/logotype-ace.svg"},
{name:"NASM",src:"https://www.nasm.org/images/nasm-logo.svg"},
{name:"ISSA",src:"https://go.issaonline.com/hubfs/BMG360_ISSA/global/logos/issa-logo.svg"},
{name:"K11",src:"https://commons.wikimedia.org/wiki/Special:Redirect/file/K11logo.svg"},
{name:"FITTR",src:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Fittr_logo.png"},
] as const;
const benefits=[[Target,"GOAL-ORIENTED","Every plan is tailored to your personal goals."],[Trophy,"RESULT DRIVEN","Progressive methods built around measurable improvement."],[UserRoundCheck,"PERSONAL ATTENTION","Individual coaching to help you perform your best."],[Users,"CONTINUOUS SUPPORT","Guidance through every step of your training journey."],[ShieldCheck,"SAFE & EFFECTIVE","Train with proper technique, structure and safety."]] as const;

export function CoachesPage(){return <main className="overflow-x-clip bg-white text-[#111111]"><SiteHeader/>
  <section className="relative isolate min-h-[580px] overflow-hidden bg-[#450004] text-white"><Image src={heroImage} alt="HR Health Club coaching floor" fill priority className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/94 via-46% to-[#450004]/18"/><div className="relative mx-auto flex min-h-[580px] w-[min(1280px,calc(100%-2rem))] items-center py-14"><Reveal className="max-w-[650px]"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/65">HOME / COACHES</p><h1 className="mt-7 font-[family-name:var(--font-display)] text-6xl font-black uppercase leading-[.88] sm:text-7xl lg:text-[84px]">OUR EXPERT<br/><span className="text-white/55">COACHES.</span></h1><div className="mt-6 h-1 w-12 bg-white"/><p className="mt-6 max-w-lg text-lg leading-8 text-white/78">Learn from the best. Train with the best. Be your best.</p><div className="mt-8 grid max-w-[650px] grid-cols-2 overflow-hidden rounded-lg border border-white/15 bg-[#450004]/55 sm:grid-cols-4">{heroFeatures.map(([Icon,label])=><div key={label} className="border-r border-white/10 p-4 text-center last:border-r-0"><Icon size={21} className="mx-auto"/><span className="mt-2 block font-[family-name:var(--font-display)] text-[10px] font-bold uppercase leading-4 text-white/70">{label}</span></div>)}</div></Reveal></div></section>

  <section className="mx-auto w-[min(1280px,calc(100%-2rem))] py-12"><Reveal className="text-center"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-[#7A0008]">MEET OUR</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase sm:text-5xl">CERTIFIED & EXPERIENCED COACHES</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-[#555555]">Our coaches are more than trainers. They are mentors who guide, motivate and push you towards your best version.</p></Reveal><div className="mt-8 grid gap-4 lg:grid-cols-3">{coachProfiles.map((coach,i)=><Reveal key={coach.slug} delay={i*.05}><article className="group h-full overflow-hidden rounded-xl border border-[#E2D6D6] bg-white transition hover:-translate-y-1 hover:border-[#7A0008]/30 hover:shadow-xl"><Link href={`/coaches/${coach.slug}`} className="block"><div className="relative h-[390px] overflow-hidden bg-[#F8EEEE]"><Image src={coach.image} alt={`${coach.name}, ${coach.role}`} fill unoptimized className="object-cover object-top transition duration-700 group-hover:scale-[1.035]" sizes="(min-width:1024px)33vw,100vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/92 via-transparent to-transparent"/><span className="absolute left-0 top-0 bg-[#7A0008] px-4 py-2 font-[family-name:var(--font-display)] text-[10px] font-bold uppercase text-white">{coach.role}</span><div className="absolute inset-x-0 bottom-0 p-5 text-white"><h3 className="font-[family-name:var(--font-display)] text-3xl font-black uppercase">{coach.name}</h3><p className="mt-1 text-xs font-semibold text-white/70">{coach.role}</p></div></div><div className="p-5"><p className="text-sm leading-6 text-[#555555]">{coach.copy}</p><div className="mt-4 grid gap-2 border-t border-[#E2D6D6] pt-4 text-xs text-[#555555]">{[coach.experience,coach.certification,coach.specialty,`Focus: ${coach.focus}`].map(item=><span key={item} className="flex items-start gap-2"><Check size={14} className="mt-0.5 shrink-0 text-[#7A0008]"/>{item}</span>)}</div><span className="mt-5 inline-flex items-center gap-2 font-[family-name:var(--font-display)] text-xs font-bold uppercase text-[#7A0008]">VIEW COACH PROFILE <ArrowRight size={14} className="transition group-hover:translate-x-1"/></span></div></Link></article></Reveal>)}</div></section>

  <section className="border-y border-[#E2D6D6] bg-[#FAF8F8] py-10"><div className="mx-auto w-[min(1280px,calc(100%-2rem))]"><Reveal className="text-center"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-[#7A0008]">CERTIFIED. TRAINED. TRUSTED.</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-black uppercase">OUR COACHES ARE CERTIFIED BY</h2></Reveal><div className="mt-7 grid grid-cols-2 overflow-hidden rounded-xl border border-[#E2D6D6] bg-white sm:grid-cols-5">{certifications.map((logo,i)=><div key={logo.name} className={`relative flex min-h-28 items-center justify-center px-5 py-6 ${i>0?"border-l border-[#E2D6D6]":""}`}><span className="absolute font-[family-name:var(--font-display)] text-2xl font-black text-[#7A0008]/25">{logo.name}</span><div className="relative z-10 h-12 w-full max-w-[145px]"><Image src={logo.src} alt={`${logo.name} certification logo`} fill unoptimized className="object-contain" sizes="145px"/></div></div>)}</div></div></section>

  <section className="mx-auto w-[min(1280px,calc(100%-2rem))] py-12"><Reveal className="text-center"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-[#7A0008]">WHY TRAIN WITH OUR COACHES?</p></Reveal><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{benefits.map(([Icon,title,text],i)=><Reveal key={title} delay={i*.035}><article className="h-full rounded-xl border border-[#E2D6D6] bg-white p-5 text-center transition hover:-translate-y-1 hover:border-[#7A0008]/30 hover:shadow-lg"><span className="mx-auto flex size-12 items-center justify-center rounded-lg bg-[#F8EEEE] text-[#7A0008]"><Icon size={21}/></span><h3 className="mt-4 font-[family-name:var(--font-display)] text-base font-black uppercase">{title}</h3><p className="mt-2 text-xs leading-5 text-[#555555]">{text}</p></article></Reveal>)}</div></section>

  <section className="mx-auto mb-14 grid w-[min(1280px,calc(100%-2rem))] overflow-hidden rounded-xl bg-[#7A0008] text-white md:grid-cols-[38%_38%_24%]"><div className="relative min-h-60"><Image src={heroImage} alt="HR Health Club personal training" fill className="object-cover" sizes="(min-width:768px)38vw,100vw"/><div className="absolute inset-0 bg-[#450004]/30"/></div><div className="flex flex-col justify-center p-7"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.15em] text-white/65">READY TO TRANSFORM</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase">YOUR BODY & LIFE?</h2><p className="mt-3 text-sm leading-6 text-white/75">Our coaches are ready to guide you towards a stronger, healthier and better you.</p></div><div className="flex flex-col justify-center gap-3 p-7"><Link href="/join" className="inline-flex items-center justify-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">JOIN HR FAMILY <ArrowRight size={16}/></Link><Link href="/free-trial" className="inline-flex items-center justify-center gap-2 rounded-md bg-[#450004] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold ring-1 ring-white/25">BOOK A FREE CONSULTATION <ArrowRight size={16}/></Link></div></section>
  <SiteFooter/><FloatingActions/>
</main>}
