import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Award, Check, ShieldCheck, Target, Trophy, UserRoundCheck, Users } from "lucide-react";
import { FloatingActions } from "@/components/floating-actions";
import { heroImage } from "@/components/home/home-data";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { coachProfiles } from "./coach-data";

const heroFeatures = [[Users, "Expert Coaches"], [Award, "Certified Professionals"], [Trophy, "Result Driven"], [Target, "Personalized Attention"]] as const;
const certificationLogos = [
  { name: "ACE", src: "https://s3.amazonaws.com/prod.skimble/photos/20898272/skimble_workout_trainer_certification_logo_s_american_council_on_exercise_ace_cpt_iphone.jpg", href: "https://www.acefitness.org/" },
  { name: "NASM", src: "https://mwcc.3dcartstores.com/assets/images/NASM%20certified%20nutrition%20coach%20.jpg", href: "https://www.nasm.org/" },
  { name: "ISSA", src: "https://go.issaonline.com/hubfs/BMG360_ISSA/global/logos/issa-logo.svg", href: "https://www.issaonline.com/" },
  { name: "K11", src: "https://commons.wikimedia.org/wiki/Special:Redirect/file/K11logo.svg", href: "https://www.k11academy.com/" },
  { name: "FITTR", src: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Fittr_logo.png", href: "https://www.fittr.com/" },
] as const;
const benefits = [[Target, "Goal-Oriented", "Every plan is tailored to your personal goals."], [Trophy, "Result Driven", "Progressive methods built around measurable improvement."], [UserRoundCheck, "Personal Attention", "Individual coaching to help you perform your best."], [Users, "Continuous Support", "Guidance through every step of your training journey."], [ShieldCheck, "Safe & Effective", "Train with proper technique, structure and safety."]] as const;

export function CoachesPage() {
  return (
    <main className="overflow-x-clip bg-white text-[#111111]">
      <SiteHeader />
      <section className="relative isolate min-h-[520px] overflow-hidden bg-[#450004] text-white"><Image src={heroImage} alt="HR Health Club coaching floor" fill priority className="object-cover object-center" sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/94 via-48% to-[#450004]/20" /><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/35 via-transparent to-transparent" /><div className="relative mx-auto flex min-h-[520px] w-[min(1280px,calc(100%-2rem))] items-center py-14"><Reveal y={22} className="max-w-[560px]"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-white/65">Home / Coaches</p><h1 className="mt-6 font-[family-name:var(--font-display)] text-6xl font-bold uppercase leading-[.88] sm:text-7xl lg:text-[82px]">Our Expert <span className="block text-white/55">Coaches.</span></h1><div className="mt-6 h-1 w-12 bg-white/80" /><p className="mt-6 max-w-md text-lg leading-8 text-white/80">Learn from the best. Train with the best. Be your best.</p><div className="mt-8 grid grid-cols-2 gap-0 sm:grid-cols-4">{heroFeatures.map(([Icon, label], index) => <div key={label} className={`px-4 first:pl-0 ${index > 0 ? "border-l border-white/20" : ""}`}><Icon size={23} className="text-white" /><span className="mt-2 block font-[family-name:var(--font-display)] text-[11px] font-bold uppercase leading-5 text-white/75">{label}</span></div>)}</div></Reveal></div></section>

      <section className="mx-auto w-[min(1280px,calc(100%-2rem))] py-14"><Reveal className="text-center"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-[#7A0008]">Meet Our</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-bold uppercase sm:text-5xl">Certified & Experienced Coaches</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-[#555555]">Our coaches are more than trainers. They are mentors who guide, motivate and push you toward your best version.</p></Reveal><div className="mt-10 grid gap-5 lg:grid-cols-3">{coachProfiles.map((coach, index) => <Reveal key={coach.slug} delay={index * 0.07}><article className="group h-full overflow-hidden rounded-xl border border-[#E2D6D6] bg-white shadow-sm transition duration-500 hover:-translate-y-1.5 hover:border-[#7A0008]/35 hover:shadow-2xl"><Link href={`/coaches/${coach.slug}`} className="block h-full"><div className="relative h-[430px] overflow-hidden bg-[#F8EEEE]"><Image src={coach.image} alt={`${coach.name}, ${coach.role}`} fill unoptimized className="object-cover object-top transition duration-700 group-hover:scale-[1.035]" sizes="(min-width:1024px) 33vw, 100vw" /><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/88 via-transparent to-transparent" /><span className="absolute left-0 top-0 bg-[#7A0008] px-4 py-2 font-[family-name:var(--font-display)] text-xs font-bold uppercase tracking-wide text-white">{coach.role}</span><div className="absolute inset-x-0 bottom-0 p-6 text-white"><h3 className="font-[family-name:var(--font-display)] text-4xl font-bold uppercase leading-none">{coach.name}</h3><p className="mt-2 text-sm font-semibold text-white/75">{coach.role}</p></div></div><div className="p-6"><p className="text-sm leading-7 text-[#555555]">{coach.copy}</p><div className="mt-5 grid gap-2 border-t border-[#E2D6D6] pt-5 text-sm text-[#555555]">{[coach.experience, coach.certification, coach.specialty, `Focus: ${coach.focus}`].map((item) => <span key={item} className="flex items-start gap-2"><Check size={15} className="mt-1 shrink-0 text-[#7A0008]" />{item}</span>)}</div><span className="mt-6 inline-flex items-center gap-2 font-[family-name:var(--font-display)] text-sm font-bold uppercase text-[#7A0008]">VIEW COACH PROFILE <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" /></span></div></Link></article></Reveal>)}</div></section>

      <section className="bg-[#FAF8F8] py-12"><div className="mx-auto w-[min(1280px,calc(100%-2rem))] rounded-xl border border-[#E2D6D6] bg-white p-6 sm:p-8"><Reveal className="text-center"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-[#7A0008]">Certified. Trained. Trusted.</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-bold uppercase">Professional Certification Ecosystem</h2></Reveal><div className="mt-8 grid grid-cols-2 overflow-hidden rounded-xl border border-[#E2D6D6] sm:grid-cols-5">{certificationLogos.map((logo, index) => <a key={logo.name} href={logo.href} target="_blank" rel="noreferrer" aria-label={`${logo.name} official website`} className={`group flex min-h-28 items-center justify-center bg-white px-5 py-6 transition duration-300 hover:bg-[#F8EEEE] ${index > 0 ? "border-l border-[#E2D6D6]" : ""}`}><div className="relative h-14 w-full max-w-[150px] transition duration-300 group-hover:scale-105"><Image src={logo.src} alt={`${logo.name} logo`} fill unoptimized className="object-contain" sizes="150px" /></div></a>)}</div></div></section>

      <section className="mx-auto w-[min(1280px,calc(100%-2rem))] py-14"><Reveal className="text-center"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-[#7A0008]">Why Train With Our Coaches?</p></Reveal><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{benefits.map(([Icon, title, text], index) => <Reveal key={title} delay={index * 0.05}><article className="group h-full rounded-xl border border-[#E2D6D6] bg-white p-5 text-center transition duration-300 hover:-translate-y-1 hover:border-[#7A0008]/30 hover:shadow-xl"><span className="mx-auto flex size-12 items-center justify-center rounded-xl bg-[#F8EEEE] text-[#7A0008] transition group-hover:bg-[#7A0008] group-hover:text-white"><Icon size={22} /></span><h3 className="mt-4 font-[family-name:var(--font-display)] text-base font-bold uppercase">{title}</h3><p className="mt-3 text-sm leading-6 text-[#555555]">{text}</p></article></Reveal>)}</div></section>

      <Reveal className="mx-auto mb-14 w-[min(1280px,calc(100%-2rem))]"><section className="group grid overflow-hidden rounded-xl bg-[#7A0008] text-white md:grid-cols-[40%_60%]"><div className="relative min-h-64 overflow-hidden"><Image src={heroImage} alt="HR Health Club personal training" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width:768px) 500px, 100vw" /><div className="absolute inset-0 bg-[#450004]/35" /></div><div className="flex flex-col justify-center p-8 sm:p-10"><p className="font-[family-name:var(--font-display)] text-xl font-bold uppercase">Ready to Transform</p><h2 className="mt-1 font-[family-name:var(--font-display)] text-4xl font-bold uppercase">Your Body & Life?</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/75">Our coaches are ready to guide you towards a stronger, healthier and better you.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/membership" className="inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008] transition hover:-translate-y-0.5 hover:bg-[#F8EEEE]">JOIN HR FAMILY <ArrowRight size={17} /></Link><Link href="/coaches/ravi#book-pt" className="inline-flex items-center gap-2 rounded-md bg-[#450004] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-white ring-1 ring-white/25 transition hover:-translate-y-0.5 hover:bg-[#5A0006]">BOOK A FREE CONSULTATION <ArrowRight size={17} /></Link></div></div></section></Reveal>
      <SiteFooter /><FloatingActions />
    </main>
  );
}
