import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Award, CalendarCheck, Check, Clock3, ShieldCheck, Target } from "lucide-react";
import { FloatingActions } from "@/components/floating-actions";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import type { CoachProfile } from "./coach-data";

export function CoachDetailPage({coach}:{coach:CoachProfile}){return <main className="overflow-x-clip bg-white text-[#111111]"><SiteHeader/>
  <section className="relative isolate min-h-[600px] overflow-hidden bg-[#450004] text-white"><Image src={coach.image} alt={`${coach.name}, ${coach.role}`} fill priority unoptimized className="object-cover object-top" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/95 via-50% to-[#450004]/24"/><div className="relative mx-auto flex min-h-[600px] w-[min(1280px,calc(100%-2rem))] items-center py-14"><Reveal className="max-w-[650px]"><Link href="/coaches" className="group inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-white/65 hover:text-white"><ArrowLeft size={14} className="transition group-hover:-translate-x-1"/>COACHES / {coach.name}</Link><p className="mt-8 font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/65">{coach.role}</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-7xl font-black uppercase leading-[.86] sm:text-8xl lg:text-[96px]">{coach.name}</h1><div className="mt-6 h-1 w-12 bg-white"/><p className="mt-6 max-w-xl text-lg leading-8 text-white/78">{coach.headline}</p><div className="mt-7 grid max-w-[620px] grid-cols-2 overflow-hidden rounded-lg border border-white/15 bg-[#450004]/55">{[coach.experience,coach.certification,coach.specialty,`Focus: ${coach.focus}`].map((item,i)=><span key={item} className={`flex min-h-16 items-start gap-2 p-4 text-sm text-white/78 ${i%2?"border-l border-white/10":""} ${i>1?"border-t border-white/10":""}`}><Check size={14} className="mt-1 shrink-0"/>{item}</span>)}</div><div className="mt-7 flex flex-wrap gap-3"><a href="#book-pt" className="inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">BOOK PT WITH {coach.name} <ArrowRight size={16}/></a><Link href="/programs" className="inline-flex items-center gap-2 rounded-md border border-white/30 bg-[#450004]/25 px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold">VIEW PROGRAMS <ArrowRight size={16}/></Link></div></Reveal></div></section>

  <section className="border-b border-[#E2D6D6] bg-white"><div className="mx-auto grid w-[min(1280px,calc(100%-2rem))] sm:grid-cols-2 lg:grid-cols-4">{[[Award,"CERTIFIED COACH"],[Target,"GOAL BASED"],[ShieldCheck,"SAFE TECHNIQUE"],[CalendarCheck,"PERSONAL TRAINING"]].map(([Icon,title],i)=><Reveal key={title as string} delay={i*.035}><div className="flex min-h-24 items-center gap-3 border-r border-[#E2D6D6] p-5"><span className="flex size-11 items-center justify-center rounded-lg bg-[#F8EEEE] text-[#7A0008]"><Icon size={20}/></span><span className="font-[family-name:var(--font-display)] text-base font-black uppercase">{title as string}</span></div></Reveal>)}</div></section>

  <section className="mx-auto grid w-[min(1280px,calc(100%-2rem))] gap-7 py-12 lg:grid-cols-[.88fr_1.12fr] lg:items-center"><Reveal><div className="relative min-h-[500px] overflow-hidden rounded-xl border border-[#E2D6D6]"><Image src={coach.image} alt={`${coach.name} coaching`} fill unoptimized className="object-cover object-top" sizes="(min-width:1024px)44vw,100vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/85 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 text-white"><p className="font-[family-name:var(--font-display)] text-xs font-bold uppercase tracking-[.15em] text-white/65">{coach.role}</p><h2 className="mt-1 font-[family-name:var(--font-display)] text-3xl font-black uppercase">TRAIN WITH {coach.name}</h2></div></div></Reveal><Reveal delay={.05}><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-[#7A0008]">ABOUT {coach.name}</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase sm:text-5xl">COACHING BUILT AROUND YOUR NEXT LEVEL.</h2><p className="mt-5 leading-8 text-[#555555]">{coach.bio}</p><div className="mt-7 grid overflow-hidden rounded-xl border border-[#E2D6D6] bg-[#FAF8F8] sm:grid-cols-2">{coach.specialties.map(item=><div key={item} className="flex items-center gap-3 border-b border-r border-[#E2D6D6] p-4 text-sm"><Check size={15} className="text-[#7A0008]"/>{item}</div>)}</div></Reveal></section>

  <section className="border-y border-[#E2D6D6] bg-[#FAF8F8] py-12"><div className="mx-auto w-[min(1180px,calc(100%-2rem))]"><Reveal className="text-center"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-[#7A0008]">PROGRAMS WITH {coach.name}</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase">CHOOSE YOUR TRAINING DIRECTION</h2></Reveal><div className="mt-7 grid gap-4 md:grid-cols-3">{coach.programs.map((program,i)=><Reveal key={program} delay={i*.04}><Link href="/programs" className="group flex h-full items-center justify-between rounded-xl border border-[#E2D6D6] bg-white p-5 transition hover:-translate-y-1 hover:border-[#7A0008]/30 hover:shadow-lg"><div><span className="font-[family-name:var(--font-display)] text-xs font-bold text-[#7A0008]">0{i+1}</span><h3 className="mt-2 font-[family-name:var(--font-display)] text-xl font-black uppercase">{program}</h3></div><ArrowRight size={19} className="text-[#7A0008] transition group-hover:translate-x-1"/></Link></Reveal>)}</div></div></section>

  <section id="book-pt" className="mx-auto w-[min(1280px,calc(100%-2rem))] scroll-mt-28 py-12"><Reveal><div className="grid overflow-hidden rounded-xl border border-[#E2D6D6] bg-white lg:grid-cols-[.42fr_.58fr]"><div className="relative min-h-[390px]"><Image src={coach.image} alt={`Book personal training with ${coach.name}`} fill unoptimized className="object-cover object-top" sizes="(min-width:1024px)42vw,100vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/65 via-transparent to-transparent"/></div><div className="flex flex-col justify-center p-8 sm:p-10"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-[#7A0008]">PERSONAL TRAINING</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase sm:text-5xl">START YOUR NEXT PHASE WITH {coach.name}.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-[#555555]">Get individual attention, technique feedback and a plan built around your current ability and target.</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><span className="flex items-center gap-3 rounded-lg bg-[#F8EEEE] p-4 text-sm"><CalendarCheck size={18} className="text-[#7A0008]"/>Coach selection preserved</span><span className="flex items-center gap-3 rounded-lg bg-[#F8EEEE] p-4 text-sm"><Clock3 size={18} className="text-[#7A0008]"/>Choose schedule in booking</span></div><Link href={`/book-pt?coach=${coach.slug}`} className="mt-6 inline-flex w-fit items-center gap-2 rounded-md bg-[#7A0008] px-6 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-white hover:bg-[#450004]">BOOK PERSONAL TRAINING <ArrowRight size={16}/></Link></div></div></Reveal></section>
  <SiteFooter/><FloatingActions/>
</main>}
