import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarCheck, Check, Clock3, Dumbbell, ShieldCheck } from "lucide-react";
import { FloatingActions } from "@/components/floating-actions";
import { heroImage } from "@/components/home/home-data";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata={title:"Book a Free Trial | HR Health Club Jodhpur",description:"Book a free gym trial or fitness consultation at HR Health Club."};
const field="w-full rounded-md border border-[#E2D6D6] bg-white px-4 py-3 text-sm outline-none transition placeholder:text-[#777] focus:border-[#7A0008] focus:ring-2 focus:ring-[#7A0008]/10";

export default function Page(){return <main className="overflow-x-clip bg-white text-[#111]"><SiteHeader/>
  <section className="relative isolate min-h-[520px] overflow-hidden bg-[#450004] text-white"><Image src={heroImage} alt="Book a free trial at HR Health Club" fill priority className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/94 via-48% to-[#450004]/18"/><div className="relative mx-auto flex min-h-[520px] w-[min(1280px,calc(100%-2rem))] items-center py-14"><Reveal className="max-w-[680px]"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/65">FREE TRIAL & CONSULTATION</p><h1 className="mt-6 font-[family-name:var(--font-display)] text-6xl font-black uppercase leading-[.88] sm:text-7xl lg:text-[82px]">START WITH<br/><span className="text-white/55">ONE GUIDED VISIT.</span></h1><div className="mt-6 h-1 w-12 bg-white"/><p className="mt-6 max-w-xl text-lg leading-8 text-white/78">Experience the gym, meet our coaches and choose the right direction before you commit.</p></Reveal></div></section>

  <section className="mx-auto grid w-[min(1180px,calc(100%-2rem))] gap-5 py-12 lg:grid-cols-[.72fr_1.28fr]"><Reveal><aside className="h-full rounded-xl bg-[#7A0008] p-7 text-white"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-white/65">WHAT TO EXPECT</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-black uppercase">YOUR FIRST HR EXPERIENCE.</h2><div className="mt-6 grid gap-4">{[[Dumbbell,"Gym tour & equipment walkthrough"],[CalendarCheck,"Preferred date and time"],[ShieldCheck,"Goal and training discussion"],[Clock3,"No-obligation consultation"]].map(([Icon,text])=><div key={text as string} className="flex items-center gap-3 border-b border-white/15 pb-4"><Icon size={20}/><span className="text-sm text-white/82">{text as string}</span></div>)}</div><p className="mt-6 text-sm leading-7 text-white/70">Choose a free gym trial, membership consultation or fitness consultation.</p></aside></Reveal><Reveal delay={.05}><div className="rounded-xl border border-[#E2D6D6] bg-white p-7"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-[#7A0008]">BOOK YOUR SLOT</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-black uppercase">TELL US HOW WE CAN HELP.</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><input className={field} placeholder="Full Name" aria-label="Full name"/><input className={field} placeholder="Phone Number" aria-label="Phone number"/><input className={field} placeholder="Email Address" aria-label="Email address"/><select className={field} aria-label="Inquiry type" defaultValue=""><option value="" disabled>Select Inquiry Type</option><option>Free Gym Trial</option><option>Membership Consultation</option><option>Fitness Consultation</option></select><input className={field} type="date" aria-label="Preferred date"/><input className={field} type="time" aria-label="Preferred time"/><textarea className={`${field} min-h-28 sm:col-span-2`} placeholder="Tell us your fitness goal" aria-label="Fitness goal"/><label className="flex items-start gap-3 text-xs leading-5 text-[#555] sm:col-span-2"><input type="checkbox" className="mt-1 accent-[#7A0008]"/><span>I agree to be contacted by HR Health Club regarding this request.</span></label><button type="button" className="inline-flex items-center justify-center gap-2 rounded-md bg-[#7A0008] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-white transition hover:bg-[#450004] sm:col-span-2">BOOK FREE TRIAL <ArrowRight size={16}/></button></div></div></Reveal></section>
  <section className="mx-auto mb-12 grid w-[min(1180px,calc(100%-2rem))] gap-3 sm:grid-cols-3">{["MEET THE COACHING TEAM","EXPERIENCE PREMIUM EQUIPMENT","GET A CLEAR NEXT STEP"].map(item=><div key={item} className="flex items-center gap-3 rounded-lg border border-[#E2D6D6] bg-[#FAF8F8] p-5 font-[family-name:var(--font-display)] text-sm font-bold"><Check size={17} className="text-[#7A0008]"/>{item}</div>)}</section>
  <section className="mx-auto mb-14 rounded-xl bg-[#7A0008] p-8 text-center text-white"><h2 className="font-[family-name:var(--font-display)] text-3xl font-black uppercase">ALREADY KNOW THE PLAN YOU WANT?</h2><Link href="/membership" className="mt-5 inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">VIEW MEMBERSHIP PLANS <ArrowRight size={16}/></Link></section>
  <SiteFooter/><FloatingActions/>
</main>}
