import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Heart, MessageCircle, Play, Video } from "lucide-react";
import { FaInstagram } from "react-icons/fa";
import { FloatingActions } from "@/components/floating-actions";
import { galleryImages, heroImage, transformations } from "@/components/home/home-data";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

const categories=["ALL GALLERY","GYM INTERIOR","EQUIPMENT","MEMBERS","WORKOUTS","EVENTS","REELS"] as const;
const rows=[
["GYM INTERIOR",galleryImages],
["EQUIPMENT",[galleryImages[1],transformations[3].image,galleryImages[2],galleryImages[3]]],
["MEMBERS",[transformations[0].image,transformations[1].image,transformations[2].image,galleryImages[0]]],
["WORKOUTS",[transformations[3].image,transformations[1].image,transformations[0].image,galleryImages[1]]],
["EVENTS",[galleryImages[0],galleryImages[2],galleryImages[1],galleryImages[3]]],
] as const;
const reels=[
["BICEP WORKOUT",transformations[0].image,"2.1K","56"],["BACK DAY MOTIVATION",transformations[1].image,"3.4K","89"],["LEG DAY INTENSITY",transformations[3].image,"2.8K","64"],["CHEST WORKOUT",transformations[2].image,"1.9K","47"],["12 WEEKS TRANSFORMATION",galleryImages[0],"4.7K","112"],["DEADLIFT PR",galleryImages[1],"2.6K","72"],["COACH TIP: PROTEIN",galleryImages[2],"1.7K","34"],["GYM LIFE",galleryImages[3],"3.0K","81"],
] as const;
const reelFilters=["ALL REELS","WORKOUTS","TRANSFORMATIONS","COACH TIPS","GYM LIFE","NUTRITION"] as const;

export function GalleryPage(){return <main className="overflow-x-clip bg-white text-[#111111]"><SiteHeader/>
  <section className="relative isolate min-h-[560px] overflow-hidden bg-[#450004] text-white"><Image src={heroImage} alt="HR Health Club gallery" fill priority className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/94 via-46% to-[#450004]/18"/><div className="relative mx-auto flex min-h-[560px] w-[min(1280px,calc(100%-2rem))] items-center py-14"><Reveal className="max-w-[620px]"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/65">GALLERY</p><h1 className="mt-6 font-[family-name:var(--font-display)] text-6xl font-black uppercase leading-[.88] sm:text-7xl lg:text-[82px]">A GLIMPSE OF<br/><span className="text-white/55">OUR WORLD.</span></h1><div className="mt-6 h-1 w-12 bg-white"/><p className="mt-6 max-w-lg text-lg leading-8 text-white/78">Explore our space, community and the energy that drives transformation every day.</p></Reveal></div></section>

  <section className="mx-auto w-[min(1280px,calc(100%-2rem))] py-9"><Reveal><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{categories.map((item,i)=><a key={item} href={item==="REELS"?"#reels":"#photos"} className={`rounded-md border px-3 py-3 text-center font-[family-name:var(--font-display)] text-xs font-bold uppercase transition hover:-translate-y-0.5 ${i===0?"border-[#7A0008] bg-[#7A0008] text-white":"border-[#E2D6D6] bg-white hover:border-[#7A0008] hover:text-[#7A0008]"}`}>{item}</a>)}</div></Reveal><div id="photos" className="mt-8 scroll-mt-28 space-y-8">{rows.map(([title,images],ri)=><Reveal key={title} delay={ri*.035}><section><div className="mb-3 flex items-center gap-4"><h2 className="font-[family-name:var(--font-display)] text-xl font-black uppercase">{title}</h2><span className="h-px w-10 bg-[#7A0008]"/><span className="ml-auto inline-flex items-center gap-2 font-[family-name:var(--font-display)] text-[10px] font-bold uppercase text-[#7A0008]">VIEW ALL <ArrowRight size={13}/></span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{images.map((src,i)=><div key={`${title}-${i}`} className="group relative h-44 overflow-hidden rounded-lg border border-[#E2D6D6]"><Image src={src} alt={`${title} at HR Health Club`} fill unoptimized className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width:1024px)25vw,50vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/45 to-transparent opacity-0 transition group-hover:opacity-100"/></div>)}</div></section></Reveal>)}</div></section>

  <section id="reels" className="scroll-mt-28 border-y border-[#E2D6D6] bg-[#FAF8F8] py-12"><div className="mx-auto w-[min(1280px,calc(100%-2rem))]"><Reveal className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-[#7A0008]">OUR INSTAGRAM REELS</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase sm:text-5xl">REAL PEOPLE. REAL RESULTS. <span className="text-[#7A0008]">REAL INSPIRATION.</span></h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#555555]">Watch. Get motivated. Transform. Follow our workouts, transformations, coach tips and gym life.</p></div><a href="https://www.instagram.com/hr_healthclub/" target="_blank" rel="noreferrer" className="inline-flex w-fit items-center gap-2 rounded-md border border-[#7A0008] bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008] transition hover:bg-[#7A0008] hover:text-white"><FaInstagram/>FOLLOW US ON INSTAGRAM</a></Reveal>
  <Reveal className="mt-7"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-6">{reelFilters.map((f,i)=><button key={f} className={`rounded-md border px-3 py-2.5 font-[family-name:var(--font-display)] text-[11px] font-bold uppercase ${i===0?"border-[#7A0008] bg-[#7A0008] text-white":"border-[#E2D6D6] bg-white text-[#555555] hover:border-[#7A0008] hover:text-[#7A0008]"}`}>{f}</button>)}</div></Reveal>
  <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{reels.map(([title,src,likes,comments],i)=><Reveal key={title} delay={i*.03}><a href="https://www.instagram.com/hr_healthclub/" target="_blank" rel="noreferrer" className="group block overflow-hidden rounded-lg border border-[#E2D6D6] bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-72 overflow-hidden"><Image src={src} alt={`${title} HR Health Club reel`} fill unoptimized className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width:1024px)25vw,50vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/90 via-transparent to-transparent"/><span className="absolute left-3 top-3 flex size-8 items-center justify-center rounded bg-white/90 text-[#7A0008]"><Video size={16}/></span><span className="absolute left-1/2 top-1/2 flex size-14 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-white/70 bg-[#450004]/45 text-white backdrop-blur-sm transition group-hover:scale-110"><Play size={22} fill="currentColor"/></span><div className="absolute inset-x-0 bottom-0 p-4 text-white"><h3 className="font-[family-name:var(--font-display)] text-base font-black uppercase">{title}</h3><div className="mt-2 flex gap-4 text-xs text-white/70"><span className="flex items-center gap-1"><Heart size={13}/>{likes}</span><span className="flex items-center gap-1"><MessageCircle size={13}/>{comments}</span></div></div></div></a></Reveal>)}</div>
  <Reveal className="mt-7"><div className="grid overflow-hidden rounded-xl border border-[#E2D6D6] bg-white grid-cols-2 lg:grid-cols-5">{[["15K+","INSTAGRAM FOLLOWERS"],["500+","REELS PUBLISHED"],["5M+","TOTAL VIEWS"],["250K+","TOTAL LIKES"],["10K+","COMMENTS & INTERACTIONS"]].map(([v,l])=><div key={l} className="border-r border-[#E2D6D6] p-5 text-center"><strong className="font-[family-name:var(--font-display)] text-2xl font-black text-[#7A0008]">{v}</strong><span className="mt-1 block text-[10px] font-bold uppercase text-[#555555]">{l}</span></div>)}</div></Reveal></div></section>

  <section className="mx-auto my-12 grid w-[min(1280px,calc(100%-2rem))] overflow-hidden rounded-xl bg-[#7A0008] text-white md:grid-cols-[38%_38%_24%]"><div className="relative min-h-60"><Image src={transformations[3].image} alt="Join HR Health Club" fill unoptimized className="object-cover" sizes="(min-width:768px)38vw,100vw"/><div className="absolute inset-0 bg-[#450004]/30"/></div><div className="flex flex-col justify-center p-7"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.15em] text-white/65">BE PART OF SOMETHING STRONGER.</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase">JOIN HR HEALTH CLUB TODAY!</h2></div><div className="flex flex-col justify-center gap-3 p-7"><Link href="/join" className="inline-flex items-center justify-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">JOIN HR FAMILY <ArrowRight size={16}/></Link><Link href="/free-trial" className="inline-flex items-center justify-center gap-2 rounded-md bg-[#450004] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold ring-1 ring-white/25">BOOK A FREE CONSULTATION <ArrowRight size={16}/></Link></div></section>
  <SiteFooter/><FloatingActions/>
</main>}
