import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Star } from "lucide-react";
import { FloatingActions } from "@/components/floating-actions";
import { heroImage, transformations } from "@/components/home/home-data";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { transformationStories } from "./transformation-data";

const filters=["ALL TRANSFORMATIONS","WEIGHT LOSS","MUSCLE GAIN","BODY RECOMPOSITION","FEMALE TRANSFORMATIONS"] as const;
const miniReviews=[["Amazing trainers, great environment and top class equipment.","ANKIT G."],["Lost 15 kgs and gained a lot of confidence.","SATYAM J."],["HR Health Club is not just a gym, it's a family.","KUNAL D."],["Best place for serious training and real transformations.","POOJA S."],["The coaches push you beyond your limits in the best way possible.","HARSH V."]] as const;

export function TransformationsPage(){return <main className="overflow-x-clip bg-white text-[#111111]"><SiteHeader/>
  <section className="relative isolate min-h-[580px] overflow-hidden bg-[#450004] text-white"><Image src={heroImage} alt="HR Health Club transformations" fill priority className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/94 via-46% to-[#450004]/18"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/45 via-transparent to-transparent"/><div className="relative mx-auto flex min-h-[580px] w-[min(1280px,calc(100%-2rem))] items-center py-14"><Reveal className="max-w-[700px]"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/65">TRANSFORMATIONS</p><h1 className="mt-6 font-[family-name:var(--font-display)] text-6xl font-black uppercase leading-[.88] sm:text-7xl lg:text-[82px]">REAL PEOPLE.<br/>REAL RESULTS.<br/><span className="text-white/55">REAL TRANSFORMATIONS.</span></h1><div className="mt-6 h-1 w-12 bg-white"/><p className="mt-6 max-w-xl text-lg leading-8 text-white/78">Consistency. Dedication. The right guidance. These are the stories of members who turned their goals into reality.</p><div className="mt-8 grid max-w-[650px] grid-cols-2 overflow-hidden rounded-lg border border-white/15 bg-[#450004]/55 backdrop-blur-sm sm:grid-cols-4">{[["500+","TRANSFORMATIONS"],["100%","DEDICATION"],["REAL PEOPLE","REAL STORIES"],["LASTING","RESULTS"]].map(([v,l])=><div key={l} className="border-r border-white/10 p-4 text-center last:border-r-0"><strong className="block font-[family-name:var(--font-display)] text-xl font-black">{v}</strong><span className="mt-1 block text-[9px] font-bold uppercase tracking-[.1em] text-white/60">{l}</span></div>)}</div></Reveal></div></section>

  <section className="mx-auto w-[min(1280px,calc(100%-2rem))] py-10"><Reveal><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{filters.map((item,i)=><button key={item} type="button" className={`rounded-md border px-4 py-3 font-[family-name:var(--font-display)] text-xs font-bold uppercase transition hover:-translate-y-0.5 ${i===0?"border-[#7A0008] bg-[#7A0008] text-white":"border-[#E2D6D6] bg-white hover:border-[#7A0008] hover:text-[#7A0008]"}`}>{item}</button>)}</div></Reveal><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{transformationStories.map((story,i)=><Reveal key={story.slug} delay={i*.035}><Link href={`/transformations/${story.slug}`} className="group block overflow-hidden rounded-xl border border-[#E2D6D6] bg-white transition hover:-translate-y-1 hover:border-[#7A0008]/30 hover:shadow-xl"><div className="relative h-72 overflow-hidden"><Image src={story.image} alt={`${story.name} transformation`} fill unoptimized className="object-cover object-top transition duration-700 group-hover:scale-105" sizes="(min-width:1280px)33vw,(min-width:768px)50vw,100vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/92 via-transparent to-transparent"/><span className="absolute left-3 top-3 rounded bg-white px-2.5 py-1 font-[family-name:var(--font-display)] text-[10px] font-bold uppercase text-[#7A0008]">BEFORE</span><span className="absolute right-3 top-3 rounded bg-[#7A0008] px-2.5 py-1 font-[family-name:var(--font-display)] text-[10px] font-bold uppercase text-white">AFTER</span><span className="absolute left-1/2 top-1/2 flex size-20 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-white/40 bg-[#450004]/78 text-center font-[family-name:var(--font-display)] text-sm font-black text-white shadow-xl">{story.result}</span><div className="absolute inset-x-0 bottom-0 p-5 text-white"><h3 className="font-[family-name:var(--font-display)] text-2xl font-black uppercase">{story.name}</h3><p className="mt-1 font-[family-name:var(--font-display)] text-xs font-bold uppercase text-white/65">{story.time} TRANSFORMATION</p></div></div><div className="p-5"><p className="text-sm leading-6 text-[#555555]">“{story.quote}”</p><div className="mt-3 flex text-amber-500">{Array.from({length:5}).map((_,n)=><Star key={n} size={13} fill="currentColor" strokeWidth={0}/>)}</div></div></Link></Reveal>)}</div></section>

  <section className="mx-auto my-12 grid w-[min(1280px,calc(100%-2rem))] overflow-hidden rounded-xl bg-[#7A0008] text-white md:grid-cols-[34%_40%_26%]"><div className="relative min-h-60"><Image src={transformations[3].image} alt="Start your transformation" fill unoptimized className="object-cover" sizes="(min-width:768px)34vw,100vw"/><div className="absolute inset-0 bg-[#450004]/25"/></div><div className="flex flex-col justify-center p-7"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.15em] text-white/65">YOUR TRANSFORMATION</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase">COULD BE NEXT!</h2><p className="mt-3 text-sm leading-6 text-white/75">With the right guidance, consistency and mindset, you can achieve more than you think.</p></div><div className="flex flex-col justify-center gap-3 p-7"><Link href="/join" className="inline-flex items-center justify-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">JOIN HR FAMILY <ArrowRight size={16}/></Link><Link href="/free-trial" className="inline-flex items-center justify-center gap-2 rounded-md bg-[#450004] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold ring-1 ring-white/25">BOOK A FREE CONSULTATION <ArrowRight size={16}/></Link></div></section>

  <section className="mx-auto w-[min(1280px,calc(100%-2rem))] pb-14"><Reveal className="text-center"><h2 className="font-[family-name:var(--font-display)] text-3xl font-black uppercase">WHAT OUR MEMBERS SAY</h2></Reveal><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{miniReviews.map(([copy,name],i)=><Reveal key={name} delay={i*.035}><article className="h-full rounded-xl border border-[#E2D6D6] bg-white p-5"><span className="font-[family-name:var(--font-display)] text-3xl text-[#7A0008]">“</span><p className="mt-1 text-sm leading-6 text-[#555555]">{copy}</p><div className="mt-4 flex items-center justify-between"><strong className="font-[family-name:var(--font-display)] text-xs uppercase">— {name}</strong><div className="flex text-amber-500">{Array.from({length:5}).map((_,n)=><Star key={n} size={11} fill="currentColor" strokeWidth={0}/>)}</div></div></article></Reveal>)}</div></section>

  <SiteFooter/><FloatingActions/>
</main>}
