import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Clock3, Target, Trophy } from "lucide-react";
import { FloatingActions } from "@/components/floating-actions";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import type { TransformationStory } from "./transformation-data";

export function TransformationDetailPage({ story }: { story: TransformationStory }) {
  return <main className="overflow-x-clip bg-white text-[#111111]">
    <SiteHeader />
    <section className="relative isolate min-h-[560px] overflow-hidden bg-[#450004] text-white"><Image src={story.image} alt={`${story.name} transformation`} fill unoptimized priority className="object-cover object-top" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/94 via-50% to-[#450004]/28"/><div className="relative mx-auto flex min-h-[560px] w-[min(1280px,calc(100%-2rem))] items-center py-14"><Reveal className="max-w-2xl"><Link href="/transformations" className="group inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-white/70 hover:text-white"><ArrowLeft size={15} className="transition group-hover:-translate-x-1"/>Transformations</Link><p className="mt-7 font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/65">{story.category}</p><h1 className="mt-3 font-[family-name:var(--font-display)] text-6xl font-bold uppercase leading-[.9] sm:text-7xl">{story.name}<span className="mt-2 block text-white/55">{story.result} · {story.time}</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/80">“{story.quote}”</p><Link href="/free-trial" className="mt-7 inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">START YOUR JOURNEY <ArrowRight size={17}/></Link></Reveal></div></section>
    <section className="border-b border-[#E2D6D6]"><div className="mx-auto grid w-[min(1180px,calc(100%-2rem))] grid-cols-2 lg:grid-cols-4">{[[Trophy,story.result,"RESULT"],[Clock3,story.time,"TIMELINE"],[Target,story.category,"FOCUS"],[Check,"Coach-Led","APPROACH"]].map(([Icon,value,label])=><div key={label as string} className="flex items-center gap-3 border-r border-[#E2D6D6] p-5"><Icon size={22} className="text-[#7A0008]"/><div><strong className="font-[family-name:var(--font-display)] text-lg uppercase">{value as string}</strong><span className="block text-[10px] font-bold uppercase tracking-wide text-[#777]">{label as string}</span></div></div>)}</div></section>
    <section className="mx-auto grid w-[min(1180px,calc(100%-2rem))] gap-10 py-16 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><div className="relative min-h-[460px] overflow-hidden rounded-xl"><Image src={story.image} alt={`${story.name} progress story`} fill unoptimized className="object-cover object-top" sizes="(min-width:1024px)45vw,100vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/75 via-transparent to-transparent"/><div className="absolute bottom-5 left-5 right-5 flex items-center justify-between rounded-lg bg-[#450004]/85 p-4 text-white"><span className="font-[family-name:var(--font-display)] text-sm font-bold uppercase">Before → After</span><strong className="font-[family-name:var(--font-display)] text-2xl">{story.result}</strong></div></div></Reveal><Reveal delay={.06}><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-[#7A0008]">The Journey</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-bold uppercase sm:text-5xl">Consistency changed everything.</h2><p className="mt-5 leading-8 text-[#555555]">{story.story}</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Starting-point assessment","Coach-led training plan","Progressive weekly structure","Regular progress reviews"].map(item=><div key={item} className="flex items-center gap-3 rounded-xl border border-[#E2D6D6] bg-[#FAF8F8] p-4 text-sm"><Check size={16} className="text-[#7A0008]"/>{item}</div>)}</div></Reveal></section>
    <section className="mx-auto mb-14 grid w-[min(1280px,calc(100%-2rem))] overflow-hidden rounded-xl bg-[#7A0008] text-white md:grid-cols-[38%_62%]"><div className="relative min-h-56"><Image src={story.image} alt="Start your HR Health Club transformation" fill unoptimized className="object-cover" sizes="(min-width:768px)38vw,100vw"/><div className="absolute inset-0 bg-[#450004]/35"/></div><div className="flex flex-col justify-center p-8"><p className="font-[family-name:var(--font-display)] text-xl font-bold uppercase">Your story could be next.</p><h2 className="mt-1 font-[family-name:var(--font-display)] text-4xl font-bold uppercase">Start with the right guidance.</h2><div className="mt-6 flex gap-3 flex-wrap"><Link href="/free-trial" className="inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">BOOK FREE TRIAL <ArrowRight size={17}/></Link><Link href="/programs" className="inline-flex items-center gap-2 rounded-md bg-[#450004] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold ring-1 ring-white/25">EXPLORE PROGRAMS <ArrowRight size={17}/></Link></div></div></section>
    <SiteFooter/><FloatingActions/>
  </main>;
}
