import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarDays, Heart, Play, Quote, Star, Trophy, Users } from "lucide-react";
import { FaGoogle } from "react-icons/fa";
import { FloatingActions } from "@/components/floating-actions";
import { heroImage, transformations } from "@/components/home/home-data";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "Testimonials & Google Reviews | HR Health Club", description: "Read member reviews and testimonials for HR Health Club Jodhpur." };

const memberStories = [
  { name: "Rohit Sharma", goal: "Weight Loss", detail: "16 Weeks Transformation", result: "-14 KG", image: transformations[0].image, copy: "The coaches at HR Health Club are just awesome. The guidance and structured training made everything easier for me." },
  { name: "Priya Mehta", goal: "Fat Loss", detail: "12 Weeks Transformation", result: "-10 KG", image: transformations[1].image, copy: "I feel stronger, healthier and more confident than ever before. The environment keeps me motivated every single day." },
  { name: "Arjun Rathore", goal: "Muscle Gain", detail: "20 Weeks Transformation", result: "+6 KG", image: transformations[2].image, copy: "Gained lean muscle and confidence. The training, coaching and support are top class." },
  { name: "Vikas Prajapat", goal: "Weight Loss", detail: "24 Weeks Transformation", result: "-18 KG", image: transformations[3].image, copy: "My stamina improved and the coaches kept me accountable throughout the process." },
  { name: "Neha Kanwar", goal: "Body Recomposition", detail: "14 Weeks Transformation", result: "-12% BODY FAT", image: transformations[1].image, copy: "It is not just about workouts. HR changed the way I look at fitness and consistency." },
  { name: "Manish Tanwar", goal: "Muscle Gain", detail: "28 Weeks Transformation", result: "+12 KG", image: transformations[0].image, copy: "The coaches push you beyond your limits and make you the best version of yourself." },
] as const;

const googleReviews = [
  ["Lonely Soul", "Excellent atmosphere, great facilities and a professional team."],
  ["Neetu Kachchhwaha", "Clean gym, quality equipment and knowledgeable supportive trainers."],
  ["Neeraj Gurjar", "Great equipment, great music and a very motivating atmosphere."],
  ["Baldev Beniwal", "One of the best fitness centres in Jodhpur with experienced trainers."],
] as const;

export default function Page() {
  return <main className="overflow-x-clip bg-white text-[#111111]"><SiteHeader/>
    <section className="relative isolate min-h-[470px] overflow-hidden bg-[#450004] text-white">
      <Image src={heroImage} alt="HR Health Club testimonials" fill priority className="object-cover" sizes="100vw"/>
      <div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/94 via-48% to-[#450004]/20"/>
      <div className="relative mx-auto flex min-h-[470px] w-[min(1280px,calc(100%-2rem))] items-center py-12"><Reveal className="max-w-[610px]"><p className="font-[family-name:var(--font-display)] text-base font-bold uppercase tracking-[.16em] text-white/75">Testimonials</p><h1 className="mt-4 font-[family-name:var(--font-display)] text-5xl font-bold uppercase leading-[.92] sm:text-6xl lg:text-7xl">Real people.<br/>Real stories.<br/><span className="text-white/55">Real results.</span></h1><div className="mt-5 h-1 w-12 bg-white"/><p className="mt-5 max-w-lg text-base leading-7 text-white/80">Hear from members who transformed their lives with the right guidance, consistent training and the HR family.</p></Reveal></div>
    </section>

    <section className="mx-auto -mt-8 relative z-10 w-[min(1200px,calc(100%-2rem))]"><Reveal><div className="grid overflow-hidden rounded-xl border border-[#E2D6D6] bg-white shadow-lg grid-cols-2 lg:grid-cols-4">{[[Quote,"500+","Happy Members"],[Star,"4.9/5","Average Rating"],[Trophy,"1000+","Success Stories"],[Heart,"Trusted","By The Community"]].map(([Icon,value,label],i)=><div key={label as string} className={`flex min-h-24 items-center justify-center gap-4 p-5 ${i>0?"border-l border-[#E2D6D6]":""}`}><Icon size={27} className="text-[#7A0008]"/><div><strong className="font-[family-name:var(--font-display)] text-2xl font-bold">{value as string}</strong><span className="block text-xs text-[#555]">{label as string}</span></div></div>)}</div></Reveal></section>

    <section className="mx-auto w-[min(1280px,calc(100%-2rem))] py-12"><Reveal className="flex items-end justify-between gap-5"><h2 className="font-[family-name:var(--font-display)] text-3xl font-bold uppercase">What our <span className="text-[#7A0008]">members say</span></h2><a href="https://maps.app.goo.gl/Yq61MGA1KXpoK991A" target="_blank" rel="noreferrer" className="hidden items-center gap-2 font-[family-name:var(--font-display)] text-xs font-bold uppercase text-[#7A0008] sm:inline-flex">VIEW ALL REVIEWS <ArrowRight size={14}/></a></Reveal><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{memberStories.map((story,index)=><Reveal key={story.name} delay={index*.035}><article className="group rounded-xl border border-[#E2D6D6] bg-white p-5 transition duration-300 hover:-translate-y-1 hover:border-[#7A0008]/40 hover:shadow-xl"><div className="flex text-amber-500">{Array.from({length:5}).map((_,i)=><Star key={i} size={15} fill="currentColor" strokeWidth={0}/>)}</div><div className="mt-4 grid grid-cols-[86px_1fr] gap-4"><div className="relative size-[86px] overflow-hidden rounded-full border-2 border-[#F8EEEE]"><Image src={story.image} alt={story.name} fill unoptimized className="object-cover object-top" sizes="86px"/></div><div><h3 className="font-[family-name:var(--font-display)] text-xl font-bold uppercase">{story.name}</h3><p className="font-[family-name:var(--font-display)] text-xs font-bold uppercase text-[#7A0008]">{story.goal}</p><p className="mt-2 text-sm leading-6 text-[#555]">{story.copy}</p></div></div><div className="mt-5 flex items-center justify-between border-t border-[#E2D6D6] pt-4 text-xs"><span className="flex items-center gap-2 font-semibold text-[#555]"><CalendarDays size={14} className="text-[#7A0008]"/>{story.detail}</span><strong className="font-[family-name:var(--font-display)] text-[#7A0008]">{story.result}</strong></div></article></Reveal>)}</div></section>

    <section className="bg-[#FAF8F8] py-12"><div className="mx-auto w-[min(1280px,calc(100%-2rem))]"><Reveal className="flex items-end justify-between gap-4"><h2 className="font-[family-name:var(--font-display)] text-3xl font-bold uppercase">Video <span className="text-[#7A0008]">Testimonials</span></h2><span className="font-[family-name:var(--font-display)] text-xs font-bold uppercase text-[#7A0008]">VIEW ALL VIDEOS <ArrowRight size={14} className="ml-1 inline"/></span></Reveal><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{memberStories.slice(0,4).map((story,index)=><Reveal key={story.name} delay={index*.04}><div className="group"><div className="relative h-56 overflow-hidden rounded-xl border border-[#E2D6D6]"><Image src={story.image} alt={`${story.name} video testimonial`} fill unoptimized className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width:1024px)25vw,50vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/65 to-transparent"/><span className="absolute left-1/2 top-1/2 flex size-14 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-white bg-[#450004]/60 text-white"><Play size={21} fill="currentColor"/></span></div><p className="mt-3 text-center text-sm font-medium text-[#555]">{story.name}&apos;s Transformation Journey</p></div></Reveal>)}</div></div></section>

    <section className="mx-auto w-[min(1280px,calc(100%-2rem))] py-12"><Reveal><div className="grid overflow-hidden rounded-xl border border-[#E2D6D6] bg-white lg:grid-cols-[.28fr_.72fr]"><div className="flex items-center gap-4 border-b border-[#E2D6D6] p-6 lg:border-b-0 lg:border-r"><span className="flex size-14 items-center justify-center rounded-full bg-[#F8EEEE] text-[#7A0008]"><FaGoogle size={25}/></span><div><p className="font-[family-name:var(--font-display)] text-xs font-bold uppercase text-[#555]">Google Rating</p><strong className="font-[family-name:var(--font-display)] text-4xl">4.9</strong><div className="mt-1 flex text-amber-500">{Array.from({length:5}).map((_,i)=><Star key={i} size={14} fill="currentColor" strokeWidth={0}/>)}</div><span className="mt-1 block text-[11px] text-[#777]">200+ Reviews</span></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4">{googleReviews.map(([name,copy],i)=><div key={name} className={`${i>0?"border-l border-[#E2D6D6]":""} p-5`}><strong className="text-sm">{name}</strong><div className="mt-1 flex text-amber-500">{Array.from({length:5}).map((_,j)=><Star key={j} size={12} fill="currentColor" strokeWidth={0}/>)}</div><p className="mt-3 text-xs leading-5 text-[#555]">{copy}</p></div>)}</div></div></Reveal></section>

    <Reveal className="mx-auto mb-14 w-[min(1280px,calc(100%-2rem))]"><section className="grid overflow-hidden rounded-xl bg-[#7A0008] text-white md:grid-cols-[34%_43%_23%]"><div className="relative min-h-56"><Image src={transformations[3].image} alt="Start your HR transformation" fill unoptimized className="object-cover" sizes="(min-width:768px)34vw,100vw"/><div className="absolute inset-0 bg-[#450004]/25"/></div><div className="flex flex-col justify-center p-7"><p className="font-[family-name:var(--font-display)] text-xl font-bold uppercase">Ready to create your own result?</p><h2 className="mt-1 font-[family-name:var(--font-display)] text-3xl font-bold uppercase">Your transformation could be next.</h2></div><div className="flex flex-col justify-center gap-3 p-6"><Link href="/join" className="inline-flex items-center justify-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">JOIN HR FAMILY <ArrowRight size={16}/></Link><Link href="/free-trial" className="inline-flex items-center justify-center gap-2 rounded-md bg-[#450004] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold ring-1 ring-white/25">BOOK FREE TRIAL <ArrowRight size={16}/></Link></div></section></Reveal>

    <SiteFooter/><FloatingActions/>
  </main>;
}
