import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, Dumbbell, Target, Users } from "lucide-react";
import { FloatingActions } from "@/components/floating-actions";
import { heroImage, programs } from "@/components/home/home-data";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { programDetails } from "./program-data";

const slugs = ["muscle-building", "fat-loss", "strength-training", "functional-training", "cardio-conditioning", "yoga-mobility"] as const;
const benefits = [[Dumbbell,"STRUCTURED TRAINING","Clear exercise direction and purposeful progression."],[Users,"COACH GUIDED","Train with support from coaches aligned to your goal."],[Target,"GOAL FOCUSED","Every program is built around a clear result."]] as const;

export function ProgramsPage() {
  return <main className="overflow-x-clip bg-white text-[#111111]">
    <SiteHeader/>

    <section className="relative isolate min-h-[590px] overflow-hidden bg-[#450004] text-white">
      <Image src={heroImage} alt="HR Health Club training programs" fill priority className="object-cover" sizes="100vw"/>
      <div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/94 via-46% to-[#450004]/18"/>
      <div className="absolute inset-0 bg-gradient-to-t from-[#450004]/45 via-transparent to-transparent"/>
      <div className="relative mx-auto flex min-h-[590px] w-[min(1280px,calc(100%-2rem))] items-center py-14">
        <Reveal className="max-w-[670px]"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/65">HOME / PROGRAMS</p><h1 className="mt-7 font-[family-name:var(--font-display)] text-6xl font-black uppercase leading-[.88] sm:text-7xl lg:text-[84px]">TRAIN SMART.<br/><span className="text-white/55">TRAIN WITH PURPOSE.</span></h1><div className="mt-6 h-1 w-12 bg-white"/><p className="mt-6 max-w-xl text-lg leading-8 text-white/78">From muscle building and fat loss to strength, cardio and mobility, choose a training direction built around your goal.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#programs-grid" className="inline-flex items-center gap-2 rounded-md bg-white px-6 py-3.5 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008] transition hover:-translate-y-0.5 hover:bg-[#F8EEEE]">EXPLORE PROGRAMS <ArrowRight size={17}/></a><Link href="/free-trial" className="inline-flex items-center gap-2 rounded-md border border-white/30 bg-[#450004]/35 px-6 py-3.5 font-[family-name:var(--font-display)] text-sm font-bold text-white transition hover:-translate-y-0.5 hover:border-white">BOOK FREE CONSULTATION <ArrowRight size={17}/></Link></div></Reveal>
      </div>
    </section>

    <section id="programs-grid" className="mx-auto w-[min(1280px,calc(100%-2rem))] scroll-mt-28 py-14">
      <Reveal className="text-center"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-[#7A0008]">OUR PROGRAMS</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase sm:text-5xl">CHOOSE YOUR TRAINING DIRECTION</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-[#555555]">Six focused paths. One standard: structured coaching and measurable progress.</p></Reveal>
      <div className="mt-9 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{programs.map((program,index)=>{const detail=programDetails.find(item=>item.slug===slugs[index]);if(!detail)return null;return <Reveal key={program.title} delay={index*.04}><article className="group overflow-hidden rounded-xl border border-[#E2D6D6] bg-white transition hover:-translate-y-1 hover:border-[#7A0008]/30 hover:shadow-xl"><Link href={`/programs/${detail.slug}`} className="block"><div className="relative h-56 overflow-hidden"><Image src={program.image} alt={program.title} fill unoptimized className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width:1280px)33vw,(min-width:768px)50vw,100vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/88 via-[#450004]/10 to-transparent"/><span className="absolute left-4 top-4 rounded bg-[#7A0008] px-3 py-1.5 font-[family-name:var(--font-display)] text-[10px] font-bold uppercase text-white">{detail.eyebrow}</span><div className="absolute inset-x-0 bottom-0 p-5 text-white"><h3 className="font-[family-name:var(--font-display)] text-2xl font-black uppercase">{program.title}</h3><p className="mt-1 text-sm text-white/75">{program.copy}</p></div></div><div className="p-5"><div className="grid gap-2">{detail.goals.slice(0,3).map(goal=><span key={goal} className="flex items-start gap-2 text-xs text-[#555555]"><Check size={14} className="mt-0.5 shrink-0 text-[#7A0008]"/>{goal}</span>)}</div><span className="mt-4 inline-flex items-center gap-2 font-[family-name:var(--font-display)] text-xs font-bold uppercase text-[#7A0008]">VIEW PROGRAM <ArrowRight size={14} className="transition group-hover:translate-x-1"/></span></div></Link><div className="border-t border-[#E2D6D6] bg-[#FAF8F8] p-4"><div className="flex items-center gap-3"><div className="relative size-12 shrink-0 overflow-hidden rounded-lg bg-[#F8EEEE]"><Image src={detail.coach.image} alt={detail.coach.name} fill unoptimized className="object-cover" sizes="48px"/></div><div className="min-w-0 flex-1"><span className="font-[family-name:var(--font-display)] text-[9px] font-bold uppercase tracking-[.12em] text-[#7A0008]">RECOMMENDED COACH</span><strong className="block font-[family-name:var(--font-display)] text-base uppercase">{detail.coach.name}</strong><span className="block truncate text-[11px] text-[#555555]">{detail.coach.role}</span></div><Link href={`/coaches/${detail.coach.slug}`} className="flex size-9 items-center justify-center rounded-full bg-[#7A0008] text-white transition hover:bg-[#450004]" aria-label={`View ${detail.coach.name}`}><ArrowRight size={15}/></Link></div><p className="mt-3 text-xs leading-5 text-[#555555]">Start your {program.title.toLowerCase()} journey with {detail.coach.name} and get coaching aligned to this path.</p></div></article></Reveal>})}</div>
    </section>

    <section className="border-y border-[#E2D6D6] bg-[#FAF8F8] py-12"><div className="mx-auto grid w-[min(1180px,calc(100%-2rem))] gap-0 overflow-hidden rounded-xl border border-[#E2D6D6] bg-white md:grid-cols-3">{benefits.map(([Icon,title,text],i)=><Reveal key={title} delay={i*.05}><article className="h-full border-b border-r border-[#E2D6D6] p-6 text-center md:border-b-0"><span className="mx-auto flex size-12 items-center justify-center rounded-lg bg-[#F8EEEE] text-[#7A0008]"><Icon size={21}/></span><h3 className="mt-4 font-[family-name:var(--font-display)] text-lg font-black uppercase">{title}</h3><p className="mt-2 text-sm leading-6 text-[#555555]">{text}</p></article></Reveal>)}</div></section>

    <section className="mx-auto my-14 grid w-[min(1280px,calc(100%-2rem))] overflow-hidden rounded-xl bg-[#7A0008] text-white md:grid-cols-[40%_60%]"><div className="relative min-h-64"><Image src={heroImage} alt="Find your HR Health Club program" fill className="object-cover" sizes="(min-width:768px)40vw,100vw"/><div className="absolute inset-0 bg-[#450004]/35"/></div><Reveal className="flex flex-col justify-center p-8 sm:p-10"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-white/65">NOT SURE WHICH PROGRAM FITS YOU?</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase">START WITH A FREE CONSULTATION.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/75">Tell us your goal and we will help you choose the right program and coach.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/contact" className="inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">TALK TO OUR TEAM <ArrowRight size={16}/></Link><Link href="/free-trial" className="inline-flex items-center gap-2 rounded-md bg-[#450004] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold ring-1 ring-white/25">BOOK FREE CONSULTATION <ArrowRight size={16}/></Link></div></Reveal></section>

    <SiteFooter/><FloatingActions/>
  </main>;
}
