import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Dumbbell, Gauge, Target, Trophy } from "lucide-react";
import { FloatingActions } from "@/components/floating-actions";
import { Reveal } from "@/components/motion/reveal";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { ProgramFaq } from "./program-faq";
import { programDetails, type ProgramDetail } from "./program-data";

const pillars=[[Dumbbell,"COACH GUIDED","Technique support and purposeful progression."],[Gauge,"PROGRESSIVE","Difficulty increases as your capacity improves."],[Target,"GOAL FOCUSED","Every phase connects directly to your target."],[Trophy,"TRACKABLE","Progress is reviewed and adjusted over time."]] as const;

export function ProgramDetailPage({program}:{program:ProgramDetail}){
  const related=programDetails.filter(item=>item.slug!==program.slug).slice(0,3);
  const faqs=[["Do I need prior gym experience?","No. The program can be scaled to your current fitness level and your coach will guide technique, structure and progression."],["How quickly should I expect progress?","Progress depends on your starting point, consistency, recovery and goal. We focus on measurable improvement rather than fixed promises."],["Can I combine this with personal training?",`Yes. ${program.coach.name} is the recommended coach for this program and can provide one-to-one support around the same goal.`],["What happens if my goal changes?","Your training direction can be reviewed and adjusted. The program is a structured starting point, not a rigid template."]] as const;

  return <main className="overflow-x-clip bg-white text-[#111111]"><SiteHeader/>
    <section className="relative isolate min-h-[600px] overflow-hidden bg-[#450004] text-white"><Image src={program.image} alt={`${program.title} program`} fill priority unoptimized className="object-cover" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-[#450004] via-[#450004]/95 via-50% to-[#450004]/20"/><div className="relative mx-auto flex min-h-[600px] w-[min(1280px,calc(100%-2rem))] items-center py-14"><Reveal className="max-w-[680px]"><Link href="/programs" className="group inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-white/65 hover:text-white"><ArrowLeft size={14} className="transition group-hover:-translate-x-1"/>PROGRAMS / {program.title}</Link><p className="mt-8 font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/65">{program.eyebrow}</p><h1 className="mt-2 font-[family-name:var(--font-display)] text-6xl font-black uppercase leading-[.88] sm:text-7xl lg:text-[86px]">{program.title}</h1><div className="mt-6 h-1 w-12 bg-white"/><p className="mt-6 max-w-xl text-lg leading-8 text-white/78">{program.intro}</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/free-trial" className="inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">BOOK FREE TRIAL <ArrowRight size={16}/></Link><Link href={`/coaches/${program.coach.slug}`} className="inline-flex items-center gap-2 rounded-md border border-white/30 bg-[#450004]/30 px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold">MEET {program.coach.name} <ArrowRight size={16}/></Link></div></Reveal></div></section>

    <section className="border-b border-[#E2D6D6] bg-white"><div className="mx-auto grid w-[min(1280px,calc(100%-2rem))] sm:grid-cols-2 lg:grid-cols-4">{pillars.map(([Icon,title,text],i)=><Reveal key={title} delay={i*.035}><article className="flex min-h-28 gap-3 border-r border-[#E2D6D6] p-5"><span className="flex size-11 shrink-0 items-center justify-center rounded-lg bg-[#F8EEEE] text-[#7A0008]"><Icon size={20}/></span><div><h2 className="font-[family-name:var(--font-display)] text-base font-black uppercase">{title}</h2><p className="mt-1 text-xs leading-5 text-[#555555]">{text}</p></div></article></Reveal>)}</div></section>

    <section className="mx-auto grid w-[min(1280px,calc(100%-2rem))] gap-7 py-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><div className="relative min-h-[470px] overflow-hidden rounded-xl border border-[#E2D6D6]"><Image src={program.image} alt={`${program.title} overview`} fill unoptimized className="object-cover" sizes="(min-width:1024px)45vw,100vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/80 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6 text-white"><p className="font-[family-name:var(--font-display)] text-xs font-bold uppercase tracking-[.18em] text-white/65">THE HR STANDARD</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-black uppercase">TRAIN WITH A PLAN. PROGRESS WITH PURPOSE.</h2></div></div></Reveal><Reveal delay={.05}><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-[#7A0008]">PROGRAM OVERVIEW</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase sm:text-5xl">BUILT AROUND YOUR GOAL.</h2><p className="mt-5 leading-8 text-[#555555]">{program.description}</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{program.goals.map(goal=><div key={goal} className="flex items-start gap-3 rounded-lg border border-[#E2D6D6] bg-[#FAF8F8] p-4 text-sm text-[#555555]"><span className="mt-0.5 flex size-6 shrink-0 items-center justify-center rounded-full bg-[#7A0008] text-white"><Check size={13}/></span>{goal}</div>)}</div></Reveal></section>

    <section className="border-y border-[#E2D6D6] bg-[#FAF8F8] py-12"><div className="mx-auto grid w-[min(1280px,calc(100%-2rem))] gap-5 lg:grid-cols-2"><Reveal><article className="h-full rounded-xl border border-[#E2D6D6] bg-white p-7"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-[#7A0008]">WHO THIS PROGRAM IS FOR</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-black uppercase">A BETTER FIT STARTS HERE.</h2><div className="mt-5 grid gap-3">{program.suitableFor.map(item=><div key={item} className="flex items-start gap-3 border-b border-[#E2D6D6] pb-3 text-sm leading-6 text-[#555555]"><Check size={15} className="mt-1 shrink-0 text-[#7A0008]"/>{item}</div>)}</div></article></Reveal><Reveal delay={.05}><article className="h-full rounded-xl bg-[#450004] p-7 text-white"><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-white/60">HOW WE APPROACH IT</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-3xl font-black uppercase">YOUR TRAINING BLUEPRINT.</h2><div className="mt-5 grid gap-3">{program.method.map((item,i)=><div key={item} className="flex items-center gap-4 rounded-lg border border-white/10 bg-white/[.06] p-4"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-white font-[family-name:var(--font-display)] text-xs font-black text-[#7A0008]">0{i+1}</span><span className="text-sm text-white/82">{item}</span></div>)}</div></article></Reveal></div></section>

    <section className="bg-[#7A0008] py-12 text-white"><div className="mx-auto grid w-[min(1180px,calc(100%-2rem))] gap-7 lg:grid-cols-[1fr_.72fr] lg:items-center"><Reveal><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-white/60">{program.coach.kicker}</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase sm:text-5xl">{program.coach.heading}</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/72">Pair the program with coach guidance so technique, progression and training decisions stay aligned with your goal.</p><div className="mt-6 flex flex-wrap gap-3"><Link href={`/coaches/${program.coach.slug}`} className="inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold text-[#7A0008]">VIEW {program.coach.name}&apos;S PROFILE <ArrowRight size={16}/></Link><Link href={`/coaches/${program.coach.slug}#book-pt`} className="inline-flex items-center gap-2 rounded-md bg-[#450004] px-5 py-3 font-[family-name:var(--font-display)] text-sm font-bold ring-1 ring-white/25">BOOK WITH {program.coach.name} <ArrowRight size={16}/></Link></div></Reveal><Reveal delay={.05}><Link href={`/coaches/${program.coach.slug}`} className="group relative block min-h-[340px] overflow-hidden rounded-xl border border-white/15"><Image src={program.coach.image} alt={program.coach.name} fill unoptimized className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width:1024px)35vw,100vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004] via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5"><span className="text-xs uppercase tracking-[.15em] text-white/60">RECOMMENDED COACH</span><h3 className="mt-1 font-[family-name:var(--font-display)] text-3xl font-black uppercase">{program.coach.name}</h3><p className="text-sm text-white/70">{program.coach.role}</p></div></Link></Reveal></div></section>

    <section className="mx-auto grid w-[min(1180px,calc(100%-2rem))] gap-8 py-12 lg:grid-cols-[.72fr_1.28fr]"><Reveal><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.2em] text-[#7A0008]">PROGRAM FAQ</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase sm:text-5xl">QUESTIONS BEFORE YOU START?</h2><p className="mt-4 max-w-md text-sm leading-7 text-[#555555]">Everything you need to know before starting this program.</p></Reveal><Reveal delay={.05}><div className="min-h-[360px]"><ProgramFaq items={faqs}/></div></Reveal></section>

    <section className="border-t border-[#E2D6D6] bg-[#FAF8F8] py-12"><div className="mx-auto w-[min(1280px,calc(100%-2rem))]"><Reveal className="flex items-end justify-between gap-4"><div><p className="font-[family-name:var(--font-display)] text-sm font-bold uppercase tracking-[.18em] text-[#7A0008]">KEEP EXPLORING</p><h2 className="mt-2 font-[family-name:var(--font-display)] text-4xl font-black uppercase">RELATED TRAINING PATHS.</h2></div><Link href="/programs" className="hidden items-center gap-2 font-[family-name:var(--font-display)] text-xs font-bold uppercase text-[#7A0008] sm:inline-flex">VIEW ALL <ArrowRight size={14}/></Link></Reveal><div className="mt-7 grid gap-4 md:grid-cols-3">{related.map((item,i)=><Reveal key={item.slug} delay={i*.04}><Link href={`/programs/${item.slug}`} className="group block overflow-hidden rounded-xl border border-[#E2D6D6] bg-white transition hover:-translate-y-1 hover:shadow-lg"><div className="relative h-44 overflow-hidden"><Image src={item.image} alt={item.title} fill unoptimized className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width:768px)33vw,100vw"/><div className="absolute inset-0 bg-gradient-to-t from-[#450004]/82 via-transparent to-transparent"/><h3 className="absolute inset-x-0 bottom-0 p-4 font-[family-name:var(--font-display)] text-xl font-black uppercase text-white">{item.title}</h3></div><div className="p-4"><span className="inline-flex items-center gap-2 font-[family-name:var(--font-display)] text-xs font-bold uppercase text-[#7A0008]">VIEW PROGRAM <ArrowRight size={13}/></span></div></Link></Reveal>)}</div></div></section>
    <SiteFooter/><FloatingActions/>
  </main>;
}
